Resolves sharing of post on social media [LBSD-2756]
liveblog/liveblog pull request #1356
Opened 2023-12-20 10:35 UTC by BrianMwangi21

Resolves [LBSD-2756] 

When a post is shared and the link opened, it shows the post shared first, with previous posts following and a counter for new updates - if they exist.

2023-12-20 10:56 UTC, BrianMwangi21 commented
Screenshot of shared post appearing as the first and the update modal with count above it
![image](https://github.com/liveblog/liveblog/assets/14116447/51d1e633-86a6-4cbe-bfc6-b4e8832fdb18)

2023-12-20 14:17 UTC, eos87 requested changes
It seems like the references to the build files are broken and not sync between the manifest and the theme file. See my screenshots

This is how it looks when I open a blog in the embed endpoint:
<img width="550" alt="image" src="https://github.com/liveblog/liveblog/assets/124766/da7ea13f-1b5e-41dc-9a60-4d4b7c286294">

and here you have the manifest and theme json files:
<img width="550" alt="image" src="https://github.com/liveblog/liveblog/assets/124766/334350c3-28b1-4094-982d-8bae1b7169a9">

<img width="550" alt="image" src="https://github.com/liveblog/liveblog/assets/124766/4d16b4a8-7653-4ce6-a738-00e620f1b720">

I'm not fully sure why this is happening but perhaps you're using `gulp-watch` without `gulp`? Please double check it. You will need to fix these references manually in both files to point to the right build and then bundle again with gulp maybe.

2023-12-20 14:17 UTC, eos87 commented on server/liveblog/themes/themes_assets/default/js/theme/view.js
> +    if(permalink) {
nit:
```suggestion
    if (permalink) {
```

2023-12-20 14:17 UTC, eos87 commented on server/liveblog/themes/themes_assets/default/js/theme/viewmodel.js
> +    if(permalink._id) {
nit:
```suggestion
    if (permalink._id) {
```

2023-12-20 14:17 UTC, eos87 commented on server/liveblog/themes/themes_assets/default/package.json
> +  "version": "3.6.77",
I think once this functionality is fully ready we should bump this to be a minor version, like `3.7.0`, it's ok for now though

2023-12-20 14:17 UTC, eos87 commented on server/liveblog/themes/themes_assets/default/theme.json
> +    "version": "3.6.77",
Same as my previous comment :)

2023-12-21 08:32 UTC, BrianMwangi21 commented on server/liveblog/themes/themes_assets/default/js/theme/view.js
> +    if(permalink) {
Resolved.

2023-12-21 08:32 UTC, BrianMwangi21 commented on server/liveblog/themes/themes_assets/default/js/theme/viewmodel.js
> +    if(permalink._id) {
Resolved.

2023-12-21 08:34 UTC, BrianMwangi21 commented
Style and scripts now match in rev-manifest and theme.json

2023-12-21 09:02 UTC, BrianMwangi21 reviewed
Requesting review for new changes,

2024-01-17 09:25 UTC, eos87 requested changes
After clicking in the alert "X new updates" the reddit embedded post does not render. Here it is an example below: 
<img width="755" alt="image" src="https://github.com/liveblog/liveblog/assets/124766/c28e5c76-9de0-4d3f-9aff-f1d9b9691c40">

Also, when you clicked a shared post and then, instead of clicking the "X new updates" alert you change the order, all the posts are shown but, the alert did not disappear:
<img width="755" alt="image" src="https://github.com/liveblog/liveblog/assets/124766/bc396bfc-1b10-4807-9127-a48225531a61">

I left a few comments, please take a look. We're getting there! 

Thanks!

2024-01-17 09:25 UTC, eos87 commented on server/liveblog/themes/themes_assets/default/js/theme/viewmodel.js
>    if (isBlogOpen) {
I think the sharing logic should work also if the blog is no longer open (archived).

2024-01-17 09:25 UTC, eos87 commented on client/app/scripts/liveblog-embed-script/sharing.ts
> -import modalHtml from './ui/shared-post-modal.html';
please also delete the `./ui/shared-post-modal.html` template

2024-01-24 15:27 UTC, eos87 commented on server/liveblog/themes/themes_assets/default/theme.json
> +    "version": "3.6.187",
This version should match the one in package.json file

2024-01-24 15:28 UTC, eos87 requested changes
There is one last comment I left regarding version. Please check it 🙏

2024-01-24 15:38 UTC, eos87 approved these changes
all good, well done!

2024-01-24 15:39 UTC, merged