[LBSD-2712] - Live streams get paused
liveblog/liveblog pull request #1366
Opened 2024-03-20 09:48 UTC by BrianMwangi21

### Purpose

This PR fixes a bug that stops live streams from auto playing when loaded.

### What has changed

- Added `autoplay=1&mute=1` to the Youtube video URL to autoplay and mute the video. 
- Added `autoplay` to the iframe allow attributes

### Steps to test

1. Navigate to the Editor's interface.
2. Click "Add content here" and select Embed. Add a link to a live Youtube video and publish
3. Click "Live" to see the Live Preview. You will see the posted video which should then autoplay.

_Note: The video will autoplay when muted. This is because most modern web browsers have implemented strict policies around autoplaying videos in an effort to improve the user experience and provide greater control of playback to viewers._

Resolves: [LBSD-2712](https://sofab.atlassian.net/browse/LBSD-2712)

2024-03-22 10:59 UTC, eos87 requested changes
There is a problem with this approach. If the user has more than one video in the timeline, it will make them all of them autoplay right after loading the embed. I think what is needed is that if the user is playing a video and a new update arrives (automated updates) the playing progress you be kept where it is and the video you continue playing without interruptions. @aleksandarjelicic please confirm if that's the expected behaviour. Thanks!

2024-03-22 10:59 UTC, eos87 commented on server/liveblog/themes/themes_assets/default/templates/template-embed-providers.html
> +            }
nit?:
```suggestion
            iframe.setAttribute('allow', 'autoplay');
            if (allowAttr && !allowAttr.includes('autoplay'))
                iframe.setAttribute('allow', allowAttr + ' autoplay');
```

2024-03-27 13:48 UTC, aleksandarjelicic commented
I confirm @eos87 proposal.

2024-04-03 07:11 UTC, BrianMwangi21 commented
I have updated the PR with the proposed changes. @aleksandarjelicic @eos87

2024-04-03 13:20 UTC, eos87 requested changes
This works but only in the Editorial tab. If you play a video and then a new update arrives, the  green button is shown at the top of the timeline to alert the user about a new update. When you click the button, it works pretty well. Nevertheless, when you change the order to "Newest first" for example and play the video once again, if a new update arrives, there is no notification (which would be fine if the `All updates are auto-applied periodically` is on in theme settings) but the video stops the playing progress. 

Please check it and let me know if you need me to clarify something.

2024-04-09 13:03 UTC, eos87 approved these changes
Looks good and works great! Nice job!

2024-04-09 13:03 UTC, merged